name: POI CICD

env:
  poi_path: apis/poi/**
  registry: docker.pkg.github.com
  repository: unhueteb-org/openhack-devops-team-gh/api-poi
  docker_path: apis/poi/web
  staging_url: https://openhackxv61mxh2poi-staging.azurewebsites.net
  prod_url: https://openhackxv61mxh2poi.azurewebsites.net
  resource_group: openhackxv61mxh2rg
  webapp_name: openhackxv61mxh2poi
  build_name: POI

on:
  push:
    branches: [ main ]
    paths: 
      - apis/poi/**  
      - .github/workflows/poi.yml
  pull_request:
    branches: [ main ]
    types: [edited, synchronize, opened, reopened]
    paths: 
      - apis/poi/**
      - .github/workflows/poi.yml
jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
    # IF PR, check a Issue has been linked
    - name: Verify Linked Issue
      if: github.event_name == 'pull_request'
      uses: hattan/verify-linked-issue-action@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.403'
    - name: Add Code Coverage Tools
      working-directory: apis/poi/tests/UnitTests
      run: dotnet add package coverlet.msbuild

    - name: Install dependencies
      run: dotnet restore apis/poi/web/poi.csproj
      
    - name: .NET Build Web
      run: dotnet build --configuration Release --no-restore apis/poi/web/poi.csproj

    - name: .NET Build Unit Tests
      run: dotnet build --configuration Release apis/poi/tests/UnitTests/UnitTests.csproj

    - name: .NET Test
      run: dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests  /p:CollectCoverage=true /p:CoverletOutput=lcov/ /p:CoverletOutputFormat=lcov
      
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: apis/poi/tests/UnitTests/lcov/coverage.info
        base-path: apis/poi
        flag-name: Unit
  #Create GH Issue if job fails 
    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
          
  #Build docker image for master branch and publish to GitHub Packages
